name: plugfox_transformers
description: >
  Contains the following transformers:
    - Simultaneous
version: 1.0.0
#author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/PlugFox/plugfox_transformers

#publish_to: 'none' 

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:

dev_dependencies:
  build_runner: ">=1.7.0 <2.0.0"
  build_web_compilers: ">=2.7.0 <3.0.0"
  mockito: ">=3.0.0 <4.0.0"  
  stack_trace: ">=1.9.2 <2.0.0"
  pedantic: '>=1.9.0 <2.0.0'
  #effective_dart: '>=1.2.1 <2.0.0'
  test: '>=1.14.2 <2.0.0'

dependency_overrides:
