name: plugfox_transformers
description: >
  Contains the following transformers:
    - Simultaneous (Serves for simultaneous parallel tasks)
version: 1.1.1
#author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/PlugFox/plugfox_transformers

#publish_to: 'none' 

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any

dependency_overrides:
